# http://kiki.to/blog/2016/02/04/talk-continuous-integration-with-lua/
language: python
sudo: false

branches:
  only:
    - master

env:
  - LUA="luajit=2.0"
  - LUA="luajit=2.1"

before_install:
  - pip install hererocks
  - hererocks lua_install -r^ --$LUA
  - export PATH=$PATH:$PWD/lua_install/bin

install:
  - luarocks install busted
  - luarocks install luacov
  - luarocks install luacov-coveralls

script:
  - busted -p .lua -m "`pwd`/?/init.lua" spec